FROM jetso 

USER root
RUN apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get -yq install \
		build-essential \
		curl \
		autoconf automake autotools-dev libtool xutils-dev \
    && rm -rf /var/lib/apt/lists/*


ENV HOME /home/jetpack
WORKDIR $HOME
USER jetpack 

#install rust toolchain
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y \
	&& echo 'source $HOME/.cargo/env' >> $HOME/.bashrc 


ENTRYPOINT ["/bin/bash"]


